/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime false` (hash: 54fd2e06166a8a77e24053d6869a073c)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
		durableNamespaces: "SecretsStore";
	}
	interface Env {
		SECRETS_STORE: DurableObjectNamespace<import("./src/worker").SecretsStore>;
	}
}
interface Env extends Cloudflare.Env {}
