/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime false` (hash: b9d5ed93b5ce9dd4f04699957ed0b648)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
		durableNamespaces: "RateLimitStore";
	}
	interface Env {
		RATE_LIMIT_STORE: DurableObjectNamespace<import("./src/worker").RateLimitStore>;
	}
}
interface Env extends Cloudflare.Env {}
